goodreads/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", landing_page, name="landing_page"),
    path("users/", include("users.urls"), name="users"),
]

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView

app_name = "users"
urlpatterns = [
    path("register", RegisterView.as_view(), name="register"),
    path("login", LoginView.as_view(), name="login"),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)

    def __str__(self):
        return self.title

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"

class BookReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    
    def __str__(self):
        return f"{self.stars_given} stars for {self.book.title} by {self.user.username}"

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password")
 
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])  # Parolni hesh qiladi
        if commit:
            user.save()
        return user

books/views.py
from django.shortcuts import render

# Create your views here.

goodreads/views.py
from django.shortcuts import render


def landing_page(request):
    return render(request, "landing.html")

users/views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views import View

from users.forms import UserCreateForm


# Create your views here.


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form,
        }
        return render(request, "users/register.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            
            return redirect('users:login')
        else:
            context = {
                "form": create_form, 
                "error": "Form is not valid."
                }
            
            return render(request, "users/register.html", context)


class LoginView(View):
    def get(self, request):
        return render(request, "users/login.html")
    

templates/landing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Landing Page</title>
  </head>
  <body>
    
    <h1>Landing Page</h1>
    
    <p><a href="{% url 'users:register' %}">Register</a> / <a href="{% url 'users:login' %}">Login</a></p>
  </body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login Page</title>
  </head>
  <body>
    <h1>Login Page</h1>
  </body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register Page</title>
  </head>
  <body>
    <h1>Register Page</h1>

    <form method="post" action="{% url "users:register" %}">
      
      {% csrf_token %}

      {{ form.as_p }}

      <p>
        Already have an account? <a href="{% url "users:login" %}">Login</a>
      </p>
      <button type="submit">Submit</button>
    </form>

  </body>
</html>